package is

// Code generated by is/gen; DO NOT EDIT."

import (
	"github.com/urfave/cli/v2"
	"stringthing/commands"
)

var (
	subCommands = []*cli.Command{
		{
			Name: "IMEI", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "ISO3166Alpha2", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "ISO3166Alpha3", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "ISO4217", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "alpha", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "alphanum", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "ascii", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "base64", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "creditcard", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "datauri", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "dialstring", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "dns", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "email", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "float", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "fullwidth", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "halfwidth", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "hexadecimal", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "hexcolor", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "host", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "int", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "ip", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "ipv4", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "ipv6", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "isbn10", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "isbn13", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "json", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "latitude", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "longitude", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "lowercase", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "mac", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "multibyte", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "notnull", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "null", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "numeric", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "port", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "printableascii", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "requri", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "requrl", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "rfc3339", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "rfc3339WithoutZone", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "rgbcolor", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "semver", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "ssn", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "ulid", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "uppercase", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "url", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "utfdigit", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "utfletter", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "utfletternum", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "utfnumeric", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "uuid", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "uuidv3", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "uuidv4", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "uuidv5", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
		{
			Name: "variablewidth", Action: doFormatAction,
			Flags: []cli.Flag{&cli.BoolFlag{Name: "verbose", Aliases: []string{"v"}, EnvVars: []string{commands.ENV_VERBOSE}}},
		},
	}
)
